"use client";

import { t, messages, money as formatMoney, errorText } from "@/lib/i18n";

import { AlertTriangle, ExternalLink, LoaderCircle, Play } from "lucide-react";
import { AmbiguitySensitivity, Day1StopDiagnostic as Report, DiagnosticComparison, DiagnosticGroup } from "@/lib/types";


const pct = (value: number | null) => value == null ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
const money = (value: number | null) => value == null ? "—" : formatMoney(value);
const price = (value: number | null) => value == null ? "—" : formatMoney(value);

type Props = { report: Report | null; loading: boolean; error: string | null; sensitivity: AmbiguitySensitivity | null; sensitivityLoading: boolean; sensitivityError: string | null; onRunSensitivity: () => void; onInspect: (backtestId: string, positionId: string) => void };

export function Day1StopDiagnostic({ report, loading, error, sensitivity, sensitivityLoading, sensitivityError, onRunSensitivity, onInspect }: Props) {
  if (loading) return <div className="panel grid min-h-72 place-items-center"><div className="flex items-center gap-2 text-sm text-cyan-200"><LoaderCircle className="animate-spin" size={18}/>{t("Building Day1 Stop diagnostic…")}</div></div>;
  if (error) return <div className="grid gap-3"><div className="flex gap-2 rounded-lg border border-rose-400/30 bg-rose-400/10 p-4 text-sm text-rose-100"><AlertTriangle size={17}/><div><strong>{t("Position-matched diagnostic unavailable")}</strong><p className="mb-0 mt-1 text-xs text-rose-100/75">{errorText(error)}</p><details><summary>{t("Technical details")}</summary><pre className="technical-raw">{error}</pre></details></div></div><section className="panel flex flex-wrap items-center justify-between gap-3 p-3 sm:p-4"><div><h3 className="m-0 text-sm font-semibold">{t("Entry Zone v2 · six-run sensitivity")}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{t("This comparison creates its own Advanced and Day1 Stop runs, so no pre-existing baseline is required.")}</p></div><button disabled={sensitivityLoading} onClick={onRunSensitivity} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-cyan-400 px-4 text-xs font-bold text-slate-950 disabled:opacity-60">{sensitivityLoading?<LoaderCircle className="animate-spin" size={15}/>:<Play size={15}/>}{t("Run six backtests")}</button></section>{sensitivityError&&<div className="rounded-md border border-rose-400/30 bg-rose-400/10 p-3 text-xs text-rose-100">{errorText(sensitivityError)}<details><summary>{t("Technical details")}</summary><pre className="technical-raw">{sensitivityError}</pre></details></div>}{sensitivity&&<SensitivityReport report={sensitivity}/>}</div>;
  if (!report) return null;
  const summary = [
    ["Day1 full stops", report.day1_full_stop_count],
    ["OHLC ambiguity", report.daily_intrabar_ambiguity_count],
    ["Unambiguous", report.group_statistics.unambiguous.count],
    ["Matched to Advanced", report.comparison.matched_count],
  ];
  return <div className="grid gap-3">
    <section className="panel flex flex-wrap items-center justify-between gap-3 p-3 sm:p-4"><div><h3 className="m-0 text-sm font-semibold">{t("Daily Intrabar Assumption Sensitivity")}</h3><p className="mb-0 mt-1 max-w-2xl text-[10px] leading-4 text-slate-500">{t("Runs the same ticker, dates, costs and strategy parameters under Conservative, OHLC Heuristic, and Favorable ordering. The heuristic is an assumption, not a real intraday path.")}</p></div><button disabled={sensitivityLoading} onClick={onRunSensitivity} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-cyan-400 px-4 text-xs font-bold text-slate-950 disabled:cursor-wait disabled:opacity-60">{sensitivityLoading?<LoaderCircle className="animate-spin" size={15}/>:<Play size={15}/>}{t("Run Ambiguity Sensitivity")}</button></section>
    {sensitivityError && <div className="rounded-md border border-rose-400/30 bg-rose-400/10 p-3 text-xs text-rose-100">{errorText(sensitivityError)}<details><summary>{t("Technical details")}</summary><pre className="technical-raw">{sensitivityError}</pre></details></div>}
    {sensitivity && <SensitivityReport report={sensitivity}/>} 
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{summary.map(([label,value])=><div className="panel p-3" key={t(label)}><p className="m-0 text-[9px] font-semibold uppercase tracking-wide text-slate-500">{t(label)}</p><p className="mb-0 mt-1 text-xl font-semibold">{value}</p></div>)}</div>
    <section className="panel p-3 sm:p-4"><header className="mb-3"><h3 className="m-0 text-sm font-semibold">{t("Backtest-level comparison")}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{t("Same inputs and shared Advanced parameters; only the Day 1 full stop differs.")}</p></header><div className="grid grid-cols-2 gap-2 lg:grid-cols-5"><Metric label={t("Existing Advanced")} value={pct(report.backtest_comparison.existing_advanced_total_return * 100)}/><Metric label={t("Day1 Stop")} value={pct(report.backtest_comparison.day1_stop_total_return * 100)}/><Metric label={t("Return difference")} value={pct(report.backtest_comparison.total_return_difference * 100)}/><Metric label={t("Final equity difference")} value={money(report.backtest_comparison.final_equity_difference)}/><Metric label={t("Matched divergences")} value={`${report.comparison.matched_count}`}/></div></section>
    <section className="panel p-3 sm:p-4"><header className="mb-3"><h3 className="m-0 text-sm font-semibold">{t("Ambiguity cohorts")}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{t("Forward returns use the selected trading-day close versus the actual stop execution price.")}</p></header><div className="grid gap-2 lg:grid-cols-2"><GroupCard title={t("Unambiguous Day1 Stops")} group={report.group_statistics.unambiguous}/><GroupCard title={t("DAILY_INTRABAR_AMBIGUITY Stops")} group={report.group_statistics.ambiguous}/></div></section>
    <section className="panel overflow-hidden"><header className="border-b border-[#223247] px-4 py-3"><h3 className="m-0 text-sm font-semibold">{t("Every DAY1_FULL_STOP")}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{report.ticker} · {report.start_date} → {report.end_date}</p></header><div className="scrollbar overflow-x-auto"><table className="table"><thead><tr><th>{t("Position")}</th><th>{t("Entry date")}</th><th>{t("Prev MA")}</th><th>{t("Entry")}</th><th>{t("Stop")}</th><th>{t("O / H / L / C")}</th><th>{t("Execution")}</th><th>{t("Loss")}</th><th>{t("Ambiguity")}</th><th>{t("Next")}</th><th>{t("5D")}</th><th>{t("10D")}</th><th>{t("20D")}</th></tr></thead><tbody>{report.stops.map(row=><tr key={row.position_id}><td><InspectButton onClick={()=>onInspect(row.backtest_id,row.position_id)}>{row.position_id}</InspectButton></td><td>{row.entry_date}</td><td>{price(row.previous_day_ma)}</td><td>{price(row.entry_price)}</td><td>{price(row.day1_stop_price)}</td><td className="whitespace-nowrap">{[row.day1_open,row.day1_high,row.day1_low,row.day1_close].map(value=>value.toFixed(2)).join(" / ")}</td><td>{price(row.execution_price)}</td><td className="text-rose-300">{pct(row.loss_pct)}</td><td>{row.daily_intrabar_ambiguity ? t("YES") : t("NO")}</td><td>{pct(row.next_day_close_return_pct)}</td><td>{pct(row.forward_5d_pct)}</td><td>{pct(row.forward_10d_pct)}</td><td>{pct(row.forward_20d_pct)}</td></tr>)}</tbody></table></div></section>
    <ComparisonSection title={t("Largest return damage")} rows={report.comparison.largest_return_damage} onInspect={onInspect}/>
    <ComparisonSection title={t("Largest improvements")} rows={report.comparison.largest_improvements} onInspect={onInspect}/>
    <details className="panel overflow-hidden"><summary className="cursor-pointer px-4 py-3 text-sm font-semibold">{messages.allDivergences(report.comparison.all_divergences.length)}</summary><ComparisonTable rows={report.comparison.all_divergences} onInspect={onInspect}/></details>
  </div>;
}

function GroupCard({ title, group }: { title: string; group: DiagnosticGroup }) {
  const items = [["Count",String(group.count)],["Average stop loss",pct(group.average_stop_loss_pct)],["Median 5D",pct(group.median_5_day_forward_return_pct)],["Median 10D",pct(group.median_10_day_forward_return_pct)],["Median 20D",pct(group.median_20_day_forward_return_pct)]];
  return <div className="rounded-md border border-[#223247] bg-[#0b131e] p-3"><h4 className="m-0 text-xs font-semibold">{t(title)}</h4><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{items.map(([label,value])=><div key={t(label)}><p className="m-0 text-[9px] uppercase text-slate-500">{t(label)}</p><p className="mb-0 mt-1 text-xs font-semibold">{value}</p></div>)}</div></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md border border-[#223247] bg-[#0b131e] p-3"><p className="m-0 text-[9px] uppercase text-slate-500">{t(label)}</p><p className="mb-0 mt-1 text-sm font-semibold">{value}</p></div>; }

function ComparisonSection({ title, rows, onInspect }: { title: string; rows: DiagnosticComparison[]; onInspect: Props["onInspect"] }) {
  return <section className="panel overflow-hidden"><header className="border-b border-[#223247] px-4 py-3"><h3 className="m-0 text-sm font-semibold">{t(title)}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{t("Variant PnL minus the matching Existing Advanced position PnL.")}</p></header><ComparisonTable rows={rows} onInspect={onInspect}/></section>;
}

function ComparisonTable({ rows, onInspect }: { rows: DiagnosticComparison[]; onInspect: Props["onInspect"] }) {
  return <div className="scrollbar overflow-x-auto"><table className="table"><thead><tr><th>{t("Entry")}</th><th>{t("Original Advanced outcome")}</th><th>{t("Day1 Stop outcome")}</th><th>{t("PnL difference")}</th><th>{t("Inspect")}</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.entry_date}-${index}`}><td>{row.entry_date}</td><td>{row.original_advanced ? `${t(row.original_advanced.exit_reason)} · ${money(row.original_advanced.net_pnl)} · ${pct(row.original_advanced.return_pct)}` : t(row.match_status)}</td><td>{t(row.day1_stop_strategy.exit_reason)} · {money(row.day1_stop_strategy.net_pnl)} · {pct(row.day1_stop_strategy.return_pct)}</td><td className={Number(row.pnl_difference)>=0?"text-emerald-300":"text-rose-300"}>{money(row.pnl_difference)}</td><td><div className="flex gap-2">{row.original_advanced&&<InspectButton onClick={()=>onInspect(row.baseline_backtest_id,row.original_advanced!.position_id)}>{t("Advanced")}</InspectButton>}<InspectButton onClick={()=>onInspect(row.variant_backtest_id,row.day1_stop_strategy.position_id)}>{t("Day1")}</InspectButton></div></td></tr>)}</tbody></table></div>;
}

function InspectButton({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} className="inline-flex items-center gap-1 whitespace-nowrap text-cyan-300 hover:text-cyan-200">{children}<ExternalLink size={11}/></button>; }

function SensitivityReport({ report }: { report: AmbiguitySensitivity }) {
  const label: Record<string,string> = { conservative: "Conservative", ohlc_heuristic: "OHLC Heuristic", favorable: "Favorable" };
  return <div className="grid gap-3">
    <section className="panel overflow-hidden"><header className="border-b border-[#223247] px-4 py-3"><h3 className="m-0 text-sm font-semibold">{messages.sensitivityTitle(report.strategy_version)}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{t("Advanced and Advanced + Day1 Stop use identical Entry Zone v2 semantics. Only ambiguous Daily OHLC ordering changes by policy.")}</p></header><div className="scrollbar overflow-x-auto"><table className="table"><thead><tr><th>{t("Strategy")}</th><th>{t("Policy")}</th><th>{t("Positions")}</th><th>{t("ENTRY_ZONE_MISSED")}</th><th>{t("Ambiguous positions")}</th><th>{t("Day1 stops")}</th><th>{t("Total return")}</th><th>{t("CAGR")}</th><th>{t("MDD")}</th><th>{t("Sharpe")}</th></tr></thead><tbody>{report.matrix.map(row=><tr key={`${row.strategy}-${row.policy}`}><td className="font-semibold">{row.strategy === "advanced" ? t("Advanced") : t("Advanced + Day1 Stop")}</td><td className="text-cyan-200">{t(label[row.policy])}</td><td>{row.positions}</td><td>{row.entry_zone_missed_count}</td><td>{row.ambiguous_positions}</td><td>{row.day1_full_stop_count}</td><td>{pct(row.total_return*100)}</td><td>{pct(row.cagr*100)}</td><td>{pct(row.max_drawdown*100)}</td><td>{row.sharpe.toFixed(2)}</td></tr>)}</tbody></table></div></section>
    <section className="panel overflow-hidden"><header className="border-b border-[#223247] px-4 py-3"><h3 className="m-0 text-sm font-semibold">{t("Same-policy matched delta")}</h3><p className="mb-0 mt-1 text-[10px] text-slate-500">{t("Advanced + Day1 Stop minus Existing Advanced; positions are matched by entry date.")}</p></header><div className="scrollbar overflow-x-auto"><table className="table"><thead><tr><th>{t("Policy")}</th><th>{t("Matched")}</th><th>{t("Advanced only")}</th><th>{t("Day1 only")}</th><th>{t("Matched PnL delta")}</th><th>{t("Total return delta")}</th><th>{t("Inspect runs")}</th></tr></thead><tbody>{report.matched_deltas.map(row=><tr key={row.policy}><td>{t(label[row.policy])}</td><td>{row.matched_positions}</td><td>{row.advanced_only_positions}</td><td>{row.day1_stop_only_positions}</td><td>{money(row.matched_net_pnl_delta)}</td><td>{pct(row.total_return_delta*100)}</td><td><div className="flex gap-2"><span className="text-[10px] text-slate-500">{t("Use History IDs")}</span></div></td></tr>)}</tbody></table></div></section>
    <details className="panel overflow-hidden"><summary className="cursor-pointer px-4 py-3 text-sm font-semibold">{messages.legacyEntries(report.legacy_entry_chasing.available ? report.legacy_entry_chasing.count : t("unavailable"))}</summary><div className="scrollbar overflow-x-auto"><table className="table"><thead><tr><th>{t("Date")}</th><th>{t("Entry")}</th><th>{t("Open")}</th><th>{t("Reference MA")}</th><th>{t("UpperEntry")}</th><th>{t("Gap above")}</th></tr></thead><tbody>{report.legacy_entry_chasing.entries.map(row=><tr key={row.date}><td>{row.date}</td><td>{price(row.entry_price)}</td><td>{price(row.open)}</td><td>{price(row.reference_ma)}</td><td>{price(row.upper_entry)}</td><td>{pct(row.gap_above_upper_entry_pct)}</td></tr>)}</tbody></table></div></details>
  </div>;
}
