"use client";

import { t, messages, money as formatMoney, num, shares, dateText, displayValue, warningText, errorText } from "@/lib/i18n";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, BarChart3, Clock3, Database, Download, FlaskConical, History, Trash2 } from "lucide-react";
import { SettingsPanel } from "@/components/SettingsPanel";
import { DrawdownChart, EquityChart, MonthlyHeatmap, StockChart } from "@/components/Charts";
import { PositionInspector } from "@/components/PositionInspector";
import { Day1StopDiagnostic } from "@/components/Day1StopDiagnostic";
import { api, ApiClientError, ApiErrorDetails } from "@/lib/api";
import { AmbiguitySensitivity, BacktestResult, Day1StopDiagnostic as DiagnosticReport, FormState, HistoryItem, PositionAudit } from "@/lib/types";
import { DEFAULT_FORM } from "@/lib/default-form";

type Tab = "Overview" | "Chart" | "Trades" | "Events" | "Parameters" | "Diagnostic" | "History";

const pctKeys = new Set(["total_return","cagr","buy_hold_return","alpha_vs_buy_hold","max_drawdown","win_rate","average_trade_return","median_trade_return"]);
const moneyKeys = new Set(["initial_capital","final_equity","average_winner","average_loser","best_trade","worst_trade","total_commission","estimated_slippage_cost"]);
const coreMetrics: Array<[string,string]> = [["total_return","Strategy return"],["buy_hold_return","Buy & hold"],["cagr","CAGR"],["max_drawdown","Max drawdown"],["sharpe_ratio","Sharpe"],["number_of_positions","Trades"],["win_rate","Win rate"],["profit_factor","Profit factor"]];
const progressStages = ["Downloading data…", "Preparing indicators…", "Running backtest…", "Calculating results…"];
const moreMetrics: Array<[string,string]> = [["final_equity","Final equity"],["alpha_vs_buy_hold","Alpha vs B&H"],["sortino_ratio","Sortino"],["calmar_ratio","Calmar"],["number_of_sell_executions","Sell executions"],["average_trade_return","Avg trade return"],["average_holding_days","Avg holding days"],["exposure_pct","Exposure %"],["total_commission","Commission"],["estimated_slippage_cost","Slippage cost"]];

function formatMetric(key: string, value: unknown) {
  if (value == null) return "—"; const number = Number(value); if (!Number.isFinite(number)) return String(value);
  if (pctKeys.has(key)) return `${(number * 100).toFixed(2)}%`; if (key === "exposure_pct") return `${number.toFixed(1)}%`; if (moneyKeys.has(key)) return formatMoney(number); return number.toFixed(key.includes("ratio") || key === "profit_factor" ? 2 : 0);
}
function download(name: string, content: string, mime = "text/plain") { const url = URL.createObjectURL(new Blob([content], {type:mime})); const a = document.createElement("a"); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }
function TranslatedRecord({value}:{value:Record<string,unknown>}) {
  return <div className="translated-record min-w-0"><dl className="grid grid-cols-2 gap-3 text-xs">{Object.entries(value).map(([key,item])=><div key={key} className="min-w-0"><dt className="text-slate-500">{t(key)}</dt><dd className="m-0 break-words">{item && typeof item === "object" && !Array.isArray(item) ? <TranslatedRecord value={item as Record<string,unknown>}/> : displayValue(key,item)}</dd></div>)}</dl><details className="mt-3 text-xs"><summary>{t("Technical details")}</summary><pre className="technical-raw">{JSON.stringify(value,null,2)}</pre></details></div>;
}
function csv(rows: Array<Record<string, unknown>>) { if (!rows.length) return ""; const keys=Object.keys(rows[0]); const escape=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`; return [keys.join(","),...rows.map(row=>keys.map(key=>escape(row[key])).join(","))].join("\n"); }

export default function Dashboard() {
  const [form, setForm] = useState(DEFAULT_FORM); const [result, setResult] = useState<BacktestResult | null>(null); const [history, setHistory] = useState<HistoryItem[]>([]);
  const [tab, setTab] = useState<Tab>("Overview"); const [running, setRunning] = useState(false); const [progressStage, setProgressStage] = useState(progressStages[0]); const [error, setError] = useState<ApiErrorDetails | null>(null); const [focus, setFocus] = useState<string>(); const [backendOnline, setBackendOnline] = useState<boolean | null>(null);
  const [auditOpen, setAuditOpen] = useState(false); const [positionAudit, setPositionAudit] = useState<PositionAudit | null>(null); const [auditLoading, setAuditLoading] = useState(false); const [auditError, setAuditError] = useState<string | null>(null);
  const [diagnostic, setDiagnostic] = useState<DiagnosticReport | null>(null); const [diagnosticLoading, setDiagnosticLoading] = useState(false); const [diagnosticError, setDiagnosticError] = useState<string | null>(null);
  const [sensitivity, setSensitivity] = useState<AmbiguitySensitivity | null>(null); const [sensitivityLoading, setSensitivityLoading] = useState(false); const [sensitivityError, setSensitivityError] = useState<string | null>(null);
  const loadHistory = () => api.history().then(rows => { setHistory(rows); setBackendOnline(true); }).catch(() => { setHistory([]); setBackendOnline(false); });
  useEffect(() => {
    api.health().then(() => setBackendOnline(true)).catch(() => setBackendOnline(false)); loadHistory();
    const query = new URLSearchParams(window.location.search);
    const identifier = query.get("backtest_id") || query.get("clone_backtest_id");
    if (!identifier) return;
    api.get(identifier).then(item => {
      const loaded = { ...DEFAULT_FORM, ...item.parameters, parameters: { ...DEFAULT_FORM.parameters, ...item.parameters.parameters } };
      setForm(loaded);
      if (query.has("backtest_id") && item.result) setResult(item.result);
    }).catch(reason => setError(reason instanceof ApiClientError ? reason.details : { message: t("Could not open backtest") }));
  }, []);
  async function run() {
    if (running) return;
    setRunning(true); setError(null); setProgressStage(progressStages[0]);
    let stage = 0; const timer = window.setInterval(() => { stage = Math.min(stage + 1, progressStages.length - 1); setProgressStage(progressStages[stage]); }, 1600);
    try { const data = await api.run(form); setResult(data); setDiagnostic(null); setDiagnosticError(null); setSensitivity(null); setSensitivityError(null); setTab("Overview"); setBackendOnline(true); await loadHistory(); }
    catch (reason) { setError(reason instanceof ApiClientError ? reason.details : { message: reason instanceof Error ? reason.message : "Backtest failed" }); setBackendOnline(reason instanceof ApiClientError && reason.details.code !== "BACKEND_UNAVAILABLE"); }
    finally { window.clearInterval(timer); setRunning(false); }
  }
  async function openHistory(id: string) { try { const item = await api.get(id); if (item.result) { setResult(item.result); setForm({ ...DEFAULT_FORM, ...item.parameters, parameters: { ...DEFAULT_FORM.parameters, ...item.parameters.parameters } }); setDiagnostic(null); setDiagnosticError(null); setSensitivity(null); setSensitivityError(null); setTab("Overview"); } } catch (reason) { setError(reason instanceof ApiClientError ? reason.details : { message: reason instanceof Error ? reason.message : "Could not open backtest" }); } }
  async function openPositionAudit(positionId: string, backtestId = result?.id) {
    if (!backtestId || !positionId) return;
    setAuditOpen(true); setPositionAudit(null); setAuditError(null); setAuditLoading(true);
    try { setPositionAudit(await api.positionAudit(backtestId, positionId)); }
    catch (reason) { setAuditError(reason instanceof ApiClientError ? reason.details.message : reason instanceof Error ? reason.message : "Could not load position audit"); }
    finally { setAuditLoading(false); }
  }
  async function selectTab(item: Tab) {
    setTab(item);
    if (item !== "Diagnostic" || !result?.id || diagnostic || diagnosticLoading) return;
    setDiagnosticLoading(true); setDiagnosticError(null);
    try { setDiagnostic(await api.day1StopDiagnostic(result.id)); }
    catch (reason) { setDiagnosticError(reason instanceof ApiClientError ? reason.details.message : reason instanceof Error ? reason.message : "Could not build diagnostic"); }
    finally { setDiagnosticLoading(false); }
  }
  async function runSensitivity() {
    if (!result?.id || sensitivityLoading) return;
    setSensitivityLoading(true); setSensitivityError(null);
    try { setSensitivity(await api.ambiguitySensitivity(result.id)); await loadHistory(); }
    catch (reason) { setSensitivityError(reason instanceof ApiClientError ? reason.details.message : reason instanceof Error ? reason.message : "Could not run sensitivity comparison"); }
    finally { setSensitivityLoading(false); }
  }
  function cloneHistory(item: HistoryItem) {
    const legacy = item.parameters as FormState & { execution_timeframe?: string };
    const { execution_timeframe: _ignoredLegacyTimeframe, ...saved } = legacy;
    setForm({ ...DEFAULT_FORM, ...saved, execution_model: "daily_conservative", parameters: { ...DEFAULT_FORM.parameters, ...saved.parameters } });
    setTab("Overview");
  }
  const tabs: Tab[] = ["Overview","Chart","Trades","Events","Parameters",...(form.strategy === "advanced_day1_stop" ? ["Diagnostic" as const] : []),"History"];
  const strategyLabel = form.strategy === "simple" ? "Simple MA Percentage Breakout" : form.strategy === "advanced" ? "Advanced MA Breakout" : "Advanced + Day1 3% Stop";
  const title = result ? `${form.ticker} · ${t(strategyLabel)}` : "MA Breakout Research Workspace";
  return <main className="min-h-screen p-2.5 sm:p-3 lg:p-4">
    <header className="mb-3 flex flex-wrap items-center justify-between gap-3 border-b border-[#223247] px-1 pb-3">
      <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-md border border-cyan-400/30 bg-cyan-400/10 text-cyan-300"><FlaskConical size={19}/></div><div><h1 className="m-0 text-lg font-semibold tracking-tight">{t("Backtest Lab")}</h1><p className="m-0 text-[11px] text-slate-500">{t("NO-LOOKAHEAD QUANT RESEARCH")}</p></div></div>
      <div className="flex flex-wrap items-center justify-end gap-2 text-xs text-slate-400"><Link href="/optimize" className="rounded-md border border-emerald-400/25 bg-emerald-400/10 px-2.5 py-1.5 font-semibold text-emerald-200 hover:bg-emerald-400/20">{t("Parameter optimization")}</Link><Link href="/ma-breakout-analytics" className="rounded-md border border-violet-400/25 bg-violet-400/10 px-2.5 py-1.5 font-semibold text-violet-200 hover:bg-violet-400/20">突破事件分析</Link><Link href="/ma-box" className="rounded-md border border-cyan-400/25 bg-cyan-400/10 px-2.5 py-1.5 font-semibold text-cyan-200 hover:bg-cyan-400/20">均線箱型研究</Link><Link href="/data" className="rounded-md border border-cyan-400/25 bg-cyan-400/10 px-2.5 py-1.5 font-semibold text-cyan-200 hover:bg-cyan-400/20">{t("Data center")}</Link><Link href="/research" className="rounded-md border border-violet-400/25 bg-violet-400/10 px-2.5 py-1.5 font-semibold text-violet-200 hover:bg-violet-400/20">{t("Research")}</Link><span className="flex items-center gap-1.5" title={backendOnline === false ? t("The service will recover automatically.") : undefined}><span className={`h-1.5 w-1.5 rounded-full ${backendOnline === false ? "bg-rose-400" : backendOnline === true ? "bg-emerald-400" : "bg-amber-300"}`}/>{backendOnline === false ? t("Service temporarily unavailable") : t("Long only")}</span><span className="flex items-center gap-1.5"><Clock3 size={13}/>{t("Daily OHLC")}</span><span className="hidden items-center gap-1.5 sm:flex"><Database size={13}/>{t("Yahoo + cache + fallback")}</span></div>
    </header>
    <div className="desktop-shell flex items-start gap-3">
      <SettingsPanel form={form} setForm={setForm} running={running} progressStage={t(progressStage)} onRun={run}/>
      <section className="min-w-0 flex-1">
        <div className="panel mb-3 flex flex-wrap items-center justify-between gap-2 px-4 py-3"><div><p className="m-0 text-[10px] font-semibold uppercase tracking-[.13em] text-slate-500">{t("Active research")}</p><h2 className="mt-0.5 text-sm font-semibold">{t(title)}</h2></div>{result && <div className="flex flex-wrap gap-2"><span className="rounded border border-[#293a50] px-2 py-1 text-[10px] text-slate-400">{String(result.data_coverage.first_strategy_date ?? "—")} → {String(result.data_coverage.last_strategy_date ?? "—")}</span><span className="rounded border border-cyan-400/20 bg-cyan-400/10 px-2 py-1 text-[10px] text-cyan-300">{t("Execution Model: Daily OHLC")}</span><span className="rounded border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">{t("Provider:")}{t(result.data_coverage.provider_display_name ?? result.data_coverage.data_provider ?? "unknown")}</span><span className="rounded border border-cyan-400/20 bg-cyan-400/10 px-2 py-1 text-[10px] text-cyan-300">{t("Intrabar:")}{t(result.summary.intrabar_assumption)}</span><span className="rounded border border-violet-400/20 bg-violet-400/10 px-2 py-1 text-[10px] text-violet-300">{result.strategy_version == null ? t("Legacy strategy version") : messages.strategyVersion(result.strategy_version)}</span></div>}</div>
        {error && <ErrorPanel error={error}/>} 
        {running && result && <div className="mb-3 flex items-center gap-3 rounded-lg border border-cyan-400/30 bg-cyan-400/10 p-3 text-sm text-cyan-100" role="status"><span className="h-4 w-4 animate-spin rounded-full border-2 border-cyan-200/30 border-t-cyan-200"/><div><strong>{t(progressStage)}</strong><div className="text-[10px] text-cyan-100/60">{t("Please keep this page open. Duplicate runs are disabled.")}</div></div></div>}
        {!result ? <EmptyState running={running}/> : <>
          <div className="summary-grid mb-3 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{coreMetrics.map(([key,label]) => <Metric key={key} label={t(label)} value={formatMetric(key, result.summary[key])} negative={key === "max_drawdown"} positive={key === "total_return" && Number(result.summary[key]) > 0}/>)}</div>
          {result.warnings.length > 0 && <div className="mb-3 flex gap-2 rounded-md border border-amber-400/25 bg-amber-400/5 px-3 py-2 text-xs text-amber-200"><AlertTriangle size={15}/><span>{result.warnings.map(warningText).join(" · ")}</span></div>}
          <div className="mb-3 grid grid-cols-3 gap-2 text-xs"><div className="panel p-3"><p className="m-0 text-[9px] uppercase text-slate-500">{t("Intrabar assumption")}</p><p className="mb-0 mt-1 font-semibold text-cyan-200">{t(result.summary.intrabar_assumption ?? form.execution_policy)}</p></div><div className="panel p-3"><p className="m-0 text-[9px] uppercase text-slate-500">{t("Ambiguous days")}</p><p className="mb-0 mt-1 font-semibold">{String(result.summary.ambiguous_days ?? 0)}</p></div><div className="panel p-3"><p className="m-0 text-[9px] uppercase text-slate-500">{t("Ambiguous positions")}</p><p className="mb-0 mt-1 font-semibold">{String(result.summary.ambiguous_positions ?? 0)}</p></div></div>
          {result.warnings.length > 0 && <details className="panel mb-3 p-3 text-xs"><summary>{t("Technical details")}</summary><pre className="technical-raw">{result.warnings.join("\n")}</pre></details>}<nav className="scrollbar mb-3 flex overflow-x-auto border-b border-[#223247]" aria-label={t("Results tabs")}>{tabs.map(item => <button key={t(item)} onClick={() => selectTab(item)} className={`shrink-0 whitespace-nowrap border-b-2 px-4 py-2.5 text-xs font-semibold ${tab===item?"border-cyan-300 text-cyan-300":"border-transparent text-slate-500 hover:text-slate-200"}`}>{t(item)}</button>)}</nav>
          {tab === "Overview" && <div className="grid gap-3 xl:grid-cols-[1.45fr_.75fr]">
            <div className="grid gap-3"><Panel title={t("Equity curve")} subtitle={t("Strategy versus buy & hold")}><EquityChart result={result}/></Panel><Panel title={t("Drawdown")} subtitle={t("Daily equity from running peak")}><DrawdownChart result={result}/></Panel></div>
            <div className="grid content-start gap-3"><Panel title={t("Performance details")}><div className="grid grid-cols-2 gap-px overflow-hidden rounded-md bg-[#223247]">{moreMetrics.map(([key,label]) => <div className="bg-[#101925] p-3" key={key}><p className="m-0 text-[10px] uppercase tracking-wide text-slate-500">{t(label)}</p><p className="mt-1 text-sm font-semibold">{formatMetric(key,result.summary[key])}</p></div>)}</div></Panel><Panel title={t("Monthly returns")}><MonthlyHeatmap result={result}/></Panel><Coverage result={result}/></div>
          </div>}
          {tab === "Chart" && <Panel title={messages.priceExecutions(form.ticker)} subtitle={t("Daily candles · volume · previous-day reference MA · execution markers")}><StockChart result={result} focusTimestamp={focus}/></Panel>}
          {tab === "Trades" && <div className="grid gap-3"><ExportBar result={result}/><Panel title={t("Position summary")} subtitle={t("Open the backend-recorded daily decision timeline for any completed position")}><DataTable rows={result.positions} actionLabel="View Details" onAction={row => openPositionAudit(String(row.position_id || ""))}/></Panel><Panel title={t("Execution log")} subtitle={t("Click a row to focus the stock chart")}><DataTable rows={result.executions} onRow={row => { setFocus(String(row.timestamp)); setTab("Chart"); }}/></Panel></div>}
          {tab === "Events" && <div className="grid gap-3"><ExportBar result={result}/><Panel title={t("Strategy event log")} subtitle={t("State transitions, triggers, reference values and ambiguity flags")}><DataTable rows={result.events}/></Panel></div>}
          {tab === "Parameters" && <div className="grid gap-3 lg:grid-cols-2"><Panel title={t("Submitted parameters")}><TranslatedRecord value={form as unknown as Record<string,unknown>}/></Panel><Panel title={t("Reproducibility record")}><TranslatedRecord value={result.reproducibility}/></Panel></div>}
          {tab === "Diagnostic" && <Day1StopDiagnostic report={diagnostic} loading={diagnosticLoading} error={diagnosticError} sensitivity={sensitivity} sensitivityLoading={sensitivityLoading} sensitivityError={sensitivityError} onRunSensitivity={runSensitivity} onInspect={(backtestId,positionId)=>openPositionAudit(positionId,backtestId)}/>}
          {tab === "History" && <Panel title={t("Backtest history")} subtitle={t("Open, delete or clone a saved parameter set")}><HistoryTable rows={history} open={openHistory} remove={async id => { await api.delete(id); loadHistory(); }} clone={cloneHistory}/></Panel>}
        </>}
      </section>
    </div>
    {auditOpen && <PositionInspector audit={positionAudit} loading={auditLoading} error={auditError} onClose={() => { setAuditOpen(false); setPositionAudit(null); setAuditError(null); }}/>} 
  </main>;
}

function EmptyState({ running }: {running:boolean}) { return <div className="panel grid min-h-[640px] place-items-center p-8 text-center"><div className="max-w-lg"><div className="mx-auto grid h-14 w-14 place-items-center rounded-xl border border-cyan-300/25 bg-cyan-300/10 text-cyan-300"><BarChart3 size={25}/></div><h2 className="mt-5 text-xl font-semibold">{running ? t("Running the event engine…") : t("Configure and run your first backtest")}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-400">{t("Daily conditions use completed prior-day MA and ATR values. Daily OHLC execution supports multi-year history and resolves unknowable same-day event order with conservative adverse-first assumptions.")}</p><div className="mt-6 grid grid-cols-3 gap-2 text-left text-xs"><Mini icon={<Activity size={15}/>} title={t("Event priority")} text="Adverse-first policy"/><Mini icon={<Database size={15}/>} title={t("Reproducible")} text="SQLite + Parquet"/><Mini icon={<History size={15}/>} title={t("Inspectable")} text="Executions & events"/></div></div></div> }
function ErrorPanel({error}:{error:ApiErrorDetails}) {
  const cache=typeof error.cache_coverage === "object" && error.cache_coverage ? `${error.cache_coverage.start||t("none")} → ${error.cache_coverage.end||t("none")} (${num(error.cache_coverage.bars??0,0)} ${t("Daily bars")})` : error.cache_coverage;
  const rows=[["Ticker",error.ticker],["Requested range",error.requested_start&&error.requested_end?`${error.requested_start} → ${error.requested_end}`:undefined],["Execution model",error.execution_model],["Market data provider",error.market_data_provider],["Daily bars",error.daily_bars_count],["Provider error",error.provider_error_code],["Cached coverage",cache],["Cache last updated",error.cache_last_updated]];
  const providerRows=Object.entries(error.provider_errors||{});
  return <div className="mb-3 rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-100" role="alert"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0" size={17}/><div className="min-w-0"><strong>{t("Backtest could not run")}</strong>{error.code&&<span className="ml-2 rounded bg-rose-300/10 px-1.5 py-0.5 text-[9px] font-semibold text-rose-200">{error.code}</span>}<p className="mb-0 mt-1 text-xs leading-5 text-rose-100/85">{errorText(error.message,error.code)}</p></div></div><div className="mt-3 grid gap-px overflow-hidden rounded bg-rose-300/15 sm:grid-cols-2">{rows.filter(([,value])=>value!==undefined&&value!==null).map(([label,value])=><div key={String(label)} className="min-w-0 bg-[#24151d] px-3 py-2"><p className="m-0 text-[9px] uppercase tracking-wide text-rose-200/50">{t(label)}</p><p className="m-0 break-words text-[11px] text-rose-100/80">{t(value)}</p></div>)}</div>{(error.message || providerRows.length>0 || error.yahoo_error || error.provider_error) && <details className="mt-3 rounded border border-rose-300/20 bg-[#24151d]/70 px-3 py-2"><summary className="cursor-pointer text-[10px] font-semibold uppercase tracking-wide text-rose-200/70">{t("Technical details")}</summary><div className="mt-2 grid gap-2 text-[11px] text-rose-100/75"><pre className="technical-raw">{error.message}</pre>{providerRows.map(([name,value])=><div key={t(name)}><span className="font-semibold text-rose-200">{t(name)}: </span>{value.message||value.error_type||value.code}</div>)}{error.yahoo_error&&<div><span className="font-semibold text-rose-200">{t("Yahoo:")}</span>{error.yahoo_error}</div>}{error.provider_error&&<div><span className="font-semibold text-rose-200">{t("Provider:")}</span>{error.provider_error}</div>}</div></details>}</div>
}
function Mini({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <div className="rounded-md border border-[#223247] bg-[#0b121c] p-3"><span className="text-cyan-300">{icon}</span><p className="mb-0 mt-2 font-semibold">{t(title)}</p><p className="m-0 text-[10px] text-slate-500">{t(text)}</p></div> }
function Metric({label,value,negative,positive}:{label:string;value:string;negative?:boolean;positive?:boolean}) { return <div className="summary-card panel min-w-0 p-3"><p className="m-0 truncate text-[9px] font-semibold uppercase tracking-[.08em] text-slate-500">{t(label)}</p><p className={`mb-0 mt-1 truncate text-lg font-semibold ${negative?"text-rose-300":positive?"text-emerald-300":"text-slate-100"}`}>{value}</p></div> }
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}) { return <section className="panel min-w-0 overflow-hidden"><header className="border-b border-[#223247] px-3 py-3 sm:px-4"><h3 className="m-0 text-sm font-semibold">{t(title)}</h3>{subtitle && <p className="mb-0 mt-0.5 text-[10px] text-slate-500">{t(subtitle)}</p>}</header><div className="p-2.5 sm:p-3">{children}</div></section> }
function Coverage({result}:{result:BacktestResult}) { return <Panel title={t("Data coverage")}><div className="grid gap-2 text-xs">{Object.entries(result.data_coverage).map(([key,value])=><div className="flex justify-between gap-3 border-b border-[#1d2a3a] pb-2" key={key}><span className="text-slate-500">{t(key)}</span><span className="max-w-[70%] break-words text-right font-medium text-slate-200">{displayValue(key,value)}</span></div>)}</div></Panel> }
function DataTable({rows,onRow,onAction,actionLabel}:{rows:Array<Record<string,unknown>>;onRow?:(row:Record<string,unknown>)=>void;onAction?:(row:Record<string,unknown>)=>void;actionLabel?:string}) {
  if (!rows.length) return <p className="p-5 text-center text-xs text-slate-500">{t("No records.")}</p>;
  const columns=Object.keys(rows[0]).filter(key=>key!=="metadata");
  const preferred=["event","event_type","side","entry_date","timestamp","price","entry_price","quantity","initial_shares","net_pnl","return_pct","reason","state_after"];
  const headline=(row:Record<string,unknown>)=>t(row.event || row.event_type || row.side || "Record");
  const compact=(key:string,value:unknown)=>displayValue(key,value);
  return <>
    <div className="desktop-table scrollbar max-h-[520px] overflow-auto"><table className="table"><thead><tr>{columns.map(c=><th key={c}>{t(c)}</th>)}{onAction&&<th>{t("Details")}</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className={onRow?"cursor-pointer":""} onClick={()=>onRow?.(row)}>{columns.map(c=><td key={c}>{compact(c,row[c])}</td>)}{onAction&&<td><button disabled={!row.position_id} className="whitespace-nowrap rounded border border-cyan-400/30 px-2 py-1 text-[10px] font-semibold text-cyan-300 disabled:border-slate-700 disabled:text-slate-600" onClick={event=>{event.stopPropagation();onAction(row);}}>{row.position_id?t(actionLabel):t("Rerun for audit")}</button></td>}</tr>)}</tbody></table></div>
    <div className="mobile-records scrollbar">{rows.map((row,i)=><details key={i} className="rounded-lg border border-[#223247] bg-[#0b131e] p-3" onClick={(event)=>{ if (onRow && !(event.target as HTMLElement).closest("summary")) onRow(row); }}><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-3"><div><span className={`text-[10px] font-bold uppercase ${String(row.side)==="BUY"?"text-cyan-300":String(row.event_type||row.event).includes("TP")?"text-amber-300":"text-rose-300"}`}>{headline(row)}</span><p className="mb-0 mt-1 text-xs font-semibold">{dateText(row.timestamp || row.entry_date)}</p></div><div className="text-right"><p className="m-0 text-sm font-semibold">{row.price!=null?formatMoney(row.price):row.net_pnl!=null?formatMoney(row.net_pnl):t("Details")}</p><p className="m-0 text-[10px] text-slate-500">{row.quantity!=null?shares(row.quantity):row.return_pct!=null?`${Number(row.return_pct).toFixed(2)}%`:t("Tap to expand")}</p></div></div></summary><div className="mt-3 grid grid-cols-2 gap-2 border-t border-[#223247] pt-3">{columns.filter(key=>preferred.includes(key)||row[key]!=null).map(key=><div key={key} className="min-w-0"><p className="m-0 truncate text-[9px] uppercase text-slate-500">{t(key)}</p><p className="m-0 break-words text-[11px] text-slate-200">{compact(key,row[key])}</p></div>)}</div>{onRow&&<button className="mt-3 w-full rounded border border-cyan-400/30 py-2 text-xs text-cyan-300" onClick={()=>onRow(row)}>{t("View on chart")}</button>}{onAction&&<button disabled={!row.position_id} className="mt-3 w-full rounded border border-cyan-400/30 py-2 text-xs font-semibold text-cyan-300 disabled:border-slate-700 disabled:text-slate-600" onClick={()=>onAction(row)}>{row.position_id?t(actionLabel):t("Rerun backtest to generate audit")}</button>}</details>)}</div>
  </>;
}
function ExportBar({result}:{result:BacktestResult}) { const options:[string,()=>void][]=[["Executions CSV",()=>download("executions.csv",csv(result.executions as unknown as Array<Record<string,unknown>>),"text/csv")],["Positions CSV",()=>download("positions.csv",csv(result.positions),"text/csv")],["Daily equity CSV",()=>download("daily-equity.csv",csv(result.equity_curve as unknown as Array<Record<string,unknown>>),"text/csv")],["Event log CSV",()=>download("events.csv",csv(result.events as unknown as Array<Record<string,unknown>>),"text/csv")],["Full JSON",()=>download("backtest.json",JSON.stringify(result,null,2),"application/json")]]; return <div className="panel flex flex-wrap items-center gap-2 px-3 py-2"><Download size={14} className="text-slate-500"/>{options.map(([name,action])=><button className="rounded border border-[#293a50] px-2 py-1 text-[10px] text-slate-300 hover:border-cyan-400/50 hover:text-cyan-300" onClick={action} key={t(name)}>{t(name)}</button>)}</div> }
function HistoryTable({rows,open,remove,clone}:{rows:HistoryItem[];open:(id:string)=>void;remove:(id:string)=>void;clone:(item:HistoryItem)=>void}) { return <div className="scrollbar overflow-auto"><table className="table"><thead><tr><th>{t("Created")}</th><th>{t("Ticker")}</th><th>{t("Strategy")}</th><th>{t("Version")}</th><th>{t("Range")}</th><th>{t("Return")}</th><th>{t("Drawdown")}</th><th>{t("Status")}</th><th>{t("Actions")}</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td>{dateText(item.created_at)}</td><td className="font-semibold">{item.ticker}</td><td>{t(item.strategy)}</td><td><span className={item.strategy_version == null ? "text-amber-300" : "text-violet-300"}>{item.strategy_version == null ? t("Legacy strategy version") : `v${item.strategy_version}`}</span></td><td>{item.start_date} → {item.end_date}</td><td>{item.total_return==null?"—":`${(item.total_return*100).toFixed(2)}%`}</td><td>{item.max_drawdown==null?"—":`${(item.max_drawdown*100).toFixed(2)}%`}</td><td>{t(item.status)}</td><td><div className="flex gap-2"><button className="text-cyan-300" onClick={()=>open(item.id)}>{t("action.open")}</button><button className="text-slate-300" onClick={()=>clone(item)}>{t("Clone")}</button><button className="text-rose-300" onClick={()=>remove(item.id)} title={t("Delete")}><Trash2 size={13}/></button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-center text-xs text-slate-500">{t("No saved backtests yet.")}</p>}</div> }
