"""Safe, cache-only rebuilding of separately persisted position audits.

This module intentionally replays a completed request in memory only to build
fresh audit snapshots.  It rejects the rebuild unless the replay produces the
same persisted strategy result.  Once verified, it writes *only* the
``position_audits`` table; executions, positions, PnL, summary, and the main
backtest result JSON remain untouched.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from numbers import Real
from typing import Any

from app.backtest.engine import BacktestEngine
from app.backtest.data_preparation import required_warmup_start
from app.backtest.models import BacktestRequest
from app.data.base import DataProvider, MarketData, validate_daily_ohlcv
from app.data.fallback import ProviderChain
from app.db.repository import BacktestRepository


class AuditRebuildError(RuntimeError):
    """A rebuild was refused before it could mutate stored audit snapshots."""


@dataclass(frozen=True)
class AuditRebuildReport:
    backtest_id: str
    ticker: str
    strategy: str
    audit_count: int
    data_provider: str
    cache_last_updated: str | None
    invariants_verified: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {
            "backtest_id": self.backtest_id,
            "ticker": self.ticker,
            "strategy": self.strategy,
            "audit_count": self.audit_count,
            "data_provider": self.data_provider,
            "cache_last_updated": self.cache_last_updated,
            "invariants_verified": list(self.invariants_verified),
        }


# These sections jointly cover the strategy's executions, position accounting,
# daily PnL/equity path, metrics, and event stream.  Provider fetch metadata and
# UI-only warnings are intentionally excluded because they are not generated by
# the strategy replay and do not change a historical trade result.
_RESULT_INVARIANT_KEYS = (
    "strategy_version",
    "summary",
    "equity_curve",
    "drawdown",
    "daily_data",
    "executions",
    "positions",
    "events",
    "monthly_returns",
)


def _normalise_result_value(value: Any) -> Any:
    """Normalise JSON-number representation without changing numerical value.

    SQLite JSON round-trips an ``initial_capital`` default as ``100000`` while
    Pydantic may materialise the same Float field as ``100000.0`` on replay.
    That representation-only distinction must not block an otherwise identical
    audit rebuild.  Booleans are handled first because they are ``int``
    subclasses in Python.
    """
    if isinstance(value, bool) or value is None or isinstance(value, str):
        return value
    if isinstance(value, Real):
        return float(value)
    if isinstance(value, list):
        return [_normalise_result_value(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _normalise_result_value(item) for key, item in value.items()}
    return value


def _canonical_json(value: Any) -> str:
    """Stable structural comparison for JSON-safe engine output."""
    return json.dumps(
        _normalise_result_value(value),
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def _invariant_differences(stored_result: dict[str, Any], rebuilt_result: dict[str, Any]) -> list[str]:
    return [
        key
        for key in _RESULT_INVARIANT_KEYS
        if _canonical_json(stored_result.get(key)) != _canonical_json(rebuilt_result.get(key))
    ]


def _complete_cached_market_data(
    data_provider: DataProvider,
    request: BacktestRequest,
) -> MarketData:
    """Read only a full cache coverage; this function never calls a provider network API."""
    start = required_warmup_start(request)
    try:
        if isinstance(data_provider, ProviderChain):
            market_data = data_provider.get_cached_market_data(
                request.ticker,
                start,
                request.end_date,
                preferred_provider=request.market_data_provider,
            )
        else:
            market_data = data_provider.get_cached_market_data(request.ticker, start, request.end_date)
    except Exception as exc:  # Defensive boundary: never fall through to a network fetch.
        raise AuditRebuildError("Unable to read cached daily data for audit rebuild.") from exc
    if market_data is None:
        raise AuditRebuildError(
            "Audit rebuild requires complete cached daily data for the original warm-up and requested range; no network download was attempted."
        )
    valid, issue = validate_daily_ohlcv(market_data.daily)
    if not valid:
        raise AuditRebuildError(f"Cached daily data is invalid for audit rebuild: {issue}.")
    return market_data


def rebuild_position_audits(
    *,
    backtest_id: str,
    repository: BacktestRepository,
    data_provider: DataProvider,
) -> AuditRebuildReport:
    """Rebuild a completed backtest's audit snapshots without changing its result.

    The cached-data replay acts as a safety gate.  A mismatch in any core
    result section raises :class:`AuditRebuildError` before the audit table is
    changed, protecting execution/PnL history from accidental semantic drift.
    """
    record = repository.get(backtest_id)
    if record is None:
        raise AuditRebuildError("Backtest was not found.")
    if record.get("status") != "COMPLETED" or not isinstance(record.get("result"), dict):
        raise AuditRebuildError("Only completed backtests with a stored result can have audits rebuilt.")

    try:
        request = BacktestRequest.model_validate(record["parameters"])
    except Exception as exc:
        raise AuditRebuildError("Stored backtest parameters are no longer valid for an audit-only replay.") from exc

    market_data = _complete_cached_market_data(data_provider, request)
    engine = BacktestEngine()
    rebuilt_result = engine.run(request, market_data.daily, market_data.provider)
    differences = _invariant_differences(record["result"], rebuilt_result)
    if differences:
        raise AuditRebuildError(
            "Audit rebuild refused because the cached replay differs from the stored backtest result: "
            + ", ".join(differences)
            + "."
        )

    stored_position_ids = {str(item.get("position_id")) for item in record["result"].get("positions", [])}
    rebuilt_position_ids = set(engine.position_audits)
    if stored_position_ids != rebuilt_position_ids:
        raise AuditRebuildError(
            "Audit rebuild refused because replayed position IDs differ from the stored result."
        )
    if not repository.replace_position_audits(backtest_id, engine.position_audits):
        raise AuditRebuildError("Backtest disappeared before audit snapshots could be replaced.")

    metadata = market_data.metadata
    return AuditRebuildReport(
        backtest_id=backtest_id,
        ticker=request.ticker,
        strategy=request.strategy.value,
        audit_count=len(engine.position_audits),
        data_provider=market_data.provider,
        cache_last_updated=metadata.get("cache_last_updated"),
        invariants_verified=_RESULT_INVARIANT_KEYS,
    )
